[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

# TODO: change to wavefront-sdk-go version
[[constraint]]
  branch = "master"
  name = "github.com/wavefronthq/wavefront-sdk-go"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
